Spring-boot-intro-solution
VArabchuk/intro pull request #2
Opened 2024-09-16 12:22 UTC by VArabchuk

2024-09-16 12:34 UTC, Elena-Bruyako requested changes
see comments

2024-09-16 12:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/IntroApplication.java
> +            public void run(String... args) throws Exception {
```suggestion
        return args -> {
```

2024-09-16 12:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +@Data
```suggestion
@Getter
@Setter
@Table(name....
```

2024-09-16 12:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +    private String title;
Add required constraints

2024-09-16 12:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-09-16 12:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +    }
```suggestion
```

2024-09-16 12:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-09-16 12:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +    private BookRepository bookRepository;
```suggestion
    private final BookRepository bookRepository;
```

2024-10-01 13:22 UTC, Elena-Bruyako requested changes

2024-10-01 13:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/model/Book.java
> +    @Column(name = "title", nullable = false)
```suggestion
    @Column(nullable = false)
```

remove attribute name for all fields

2024-10-01 13:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't save book '" + book + "' to DB", e);
```suggestion
            throw new DataProcessingException("Can't save book '" + book + "' to DB", e);
```

2024-10-01 13:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't find all books from DB", e);
```suggestion
            throw new DataProcessingException("Can't find all books from DB", e);
```

2024-10-01 13:22 UTC, Elena-Bruyako commented on src/test/java/mate/academy/intro/IntroApplicationTests.java
> +	@Test
refactor format (tabulation)

2024-10-02 08:43 UTC, okuzan approved these changes

2024-10-02 09:22 UTC, merged