Add pagination, sorting and swagger
VArabchuk/intro pull request #7
Opened 2024-10-29 17:20 UTC by VArabchuk

2024-10-29 19:53 UTC, sarakhmen requested changes
I don't see swagger configuration within this PR. Could you please expose it here?

2024-10-29 19:53 UTC, sarakhmen commented on src/main/java/mate/academy/intro/controller/BookController.java
> +    public List<BookDto> getAll(Pageable pageable) {
please add default pageable values

2024-10-29 19:53 UTC, sarakhmen commented on src/main/java/mate/academy/intro/controller/BookController.java
>          return bookService.search(searchParameters);
what about pagination here?

2024-10-31 09:44 UTC, okuzan requested changes

2024-10-31 09:44 UTC, okuzan commented on src/main/java/mate/academy/intro/controller/BookController.java
> +    public List<BookDto> getAll(Pageable pageable) {
```suggestion
    public List<BookDto> getAll(@PageableDefault(page = 0, size = 10) Pageable pageable) {

```

2024-10-31 09:44 UTC, okuzan commented on src/main/java/mate/academy/intro/controller/BookController.java
>      public List<BookDto> searchBooks(BookSearchParametersDto searchParameters) {
```suggestion
    public List<BookDto> searchBooks(BookSearchParametersDto searchParameters, @PageableDefault(page = 0, size = 10) Pageable pageable) {

```

2024-11-02 09:37 UTC, okuzan approved these changes

2024-11-14 18:05 UTC, merged